Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60
  ContextTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  UploadSavePath: storage/uploads
  UploadServerUrl: http://127.0.0.1:8000/static
  UploadImageMaxSize: 5 # MB
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png
Database:
  DBType: mysql
  Username: root
  Password: ""
  Host: 127.0.0.1:3306
  DBName: blog
  TablePrefix: blog_
  Charset: utf8
  ParseTime: true
  MaxIdleConns: 10
  MaxOpenConns: 30
Jwt:
  Secret: eddycjy
  Issuer: blog-service
  Expire: 7200
Email:
  Host: smtp.qq.com
  Port: 465
  UserName: 610808724@qq.com
  Password: eojorutxgerzbccf
  IsSSL: true
  From: 610808724@qq.com
  To:
    - rhzx3519@gmail.com
